### ISSUE TITLE
Add an ABOUT US page to the app.

### ISSUE THREAD

**Issue by AryanShinde** [mlscvitpune/Development-App#10]
Add a about us page to the options menu selected to the main activity. For information to be put up in the about us page refer the LinkedIn account for MLSC VIT Pune.

**Comment by ashishfargade** [comment]
@AryanShinde I would like contribute to this: Add an ABOUT US page to the app #10. Can you please assign me the same.

**Comment by AryanShinde** [comment]
Sure @ashishfargade you can start working on it. Assigning it to you. Best of luck!
