### ISSUE TITLE
Add google Sign-In and Sign-Out Functionality to the app

### ISSUE THREAD

**Issue by AryanShinde** [mlscvitpune/Development-App#11]
Sign-In when user clicks Sign In button on the navigation drawer, Sign-out when user clicks Sign out. Once user is Signed In then update Header View of navigation drawer. replace image with google account profile image, name with profile name and email with account email.

**Comment by AtharvKinage** [comment]
Hey @gokhalevedant06  I want to work on this issue can you please assign me?
