### ISSUE TITLE
Create Splash Screen for the app.

### ISSUE THREAD

**Issue by AryanShinde** [mlscvitpune/Development-App#12]
U can use any logo you feel best for the app.

**Comment by Manas-33** [comment]
Hey @AryanShinde can I work on this?

**Comment by omsurase** [comment]
Hey @AryanShinde  can i work on this?

**Comment by AtharvKinage** [comment]
Hey @gokhalevedant06 I want to work on this issue can you please assign me?

**Comment by AryanShinde** [comment]
@Manas-33 you already have a pr to work on. @omsurase sure you can go ahead with it. Best of luck!

**Comment by AryanShinde** [comment]
Yes, please do the required changes.

**Comment by omsurase** [comment]
There is a problem with PULL_REQUEST_TEMPLATE.md too.
these changes were merged in pr(that fixes #13 )
![image](https://user-images.githubusercontent.com/98473361/194349411-48517dd0-7c75-498e-b0ab-67be1e349086.png)

## which results in 

![image](https://user-images.githubusercontent.com/98473361/194349596-257cc316-e9c7-44d8-bd6b-a799cbfa28a9.png)
![image](https://user-images.githubusercontent.com/98473361/194349648-c946de57-c025-4ea9-9d59-56ea1db62e50.png)

I have cleared this , and I'm doing a combined pr for  the gradle build fix , pull request template correction  and a new animated splash screen
