### ISSUE TITLE
Design a appropriate App logo.

### ISSUE THREAD

**Issue by AryanShinde** [mlscvitpune/Development-App#3]
The same logo should appear on the splash screen.

**Comment by Manas-33** [comment]
Can I work on this issue @AryanShinde ?

**Comment by AryanShinde** [comment]
Yup, Assigning it to you, Best of luck!

**Comment by Manas-33** [comment]
These are some logos I made, 
Style 1:
<img width="310" alt="Frame 4" src="https://user-images.githubusercontent.com/98868132/194311995-a743aec0-83ef-405e-a55f-750bfeb24e85.png">
Style 2:
<img width="310" alt="logo" src="https://user-images.githubusercontent.com/98868132/194312004-25efe3cf-3282-4c4f-839c-950730c13e95.png">
Style 3:
![Frame 2](https://user-images.githubusercontent.com/98868132/194311982-73b2241e-2b46-4a98-b31c-79b5e628ab70.png)
