### ISSUE TITLE
Fill the Profile fragment with the google account details.

### ISSUE THREAD

**Issue by AryanShinde** [mlscvitpune/Development-App#5]
One the users signs in with google account, display details like profile image, display name, email in the profile fragment with proper UI. if user is not signed In yet then display Sign In as Guest and display Image of a guest and display name as guest and have some value for email.

**Comment by RahulSoni0** [comment]
can i work on this issue
?

**Comment by AryanShinde** [comment]
sure @RahulSoni0, Assigning it to you, best of luck!

**Comment by RahulSoni0** [comment]
hey , this repo has an issue
auto complete is not working  is not working in android studio for this particular project , in rest of all my projects it is working fine, **sorry** i am unable contribute to this project.

**Comment by noobshubham** [comment]
can you please assign this to me?

**Comment by noobshubham** [comment]
also wanted to ask that there'e no option to login with google in this app (forked the latest commit)

**Comment by omsurase** [comment]
hey @noobshubham, sign-in is implemented in the sidebar from where you can sign in for the app and I think this is also used for logging into the app, also currently person's details(extracted from email id) are not visible in the sidebar so it's hard to know if someone is successfully logged in the app.

**Comment by noobshubham** [comment]
ooh, checked and found its working. earlier I was trying to find something similar to firebase auth and when didn't find anything thought its not there. Thanks for Correction Mate! Can we connect to some other irc for better connectivity?

**Comment by noobshubham** [comment]
Check Out The UI: https://imgur.com/a/sF5UADS

**Comment by omsurase** [comment]
@noobshubham you'll have to ask the repo maintainers about any changes of that type .

**Comment by noobshubham** [comment]
> @noobshubham you'll have to ask the repo maintainers about any changes of that type .

following this guideline https://github.com/mlscvitpune/Development-App/issues/5#issue-1392655697
