### ISSUE TITLE
Get the last Increment count even after we switch between fragments.

### ISSUE THREAD

**Issue by AryanShinde** [mlscvitpune/Development-App#8]
As of now if u update the counter using the increment counter floating action button, the count is lost and reset to 0 as we switch between the fragments. Solve this issue to have the same counter value displayed irrespective or switching fragments.

**Comment by V9vek** [comment]
Hi @AryanShinde 👋🏻
I would like to work on this, if the issue is open for contribution, please assign it to me 👩🏻‍💻

**Comment by AryanShinde** [comment]
sure @V9vek, you can work on it. Assigning it to you, Best of luck!

**Comment by AryanShinde** [comment]
Yess, you can follow CONTRIBUTING.md file to help you raise a PR and fill the PR template while you raise a PR (It's an automated generated template, just do as directed on the template and you are good to go).

**Comment by V9vek** [comment]
I have opened 😉 the PR #19 
Take a look and merge if it solves the issue
Please add the required tags for `Hacktoberfest` 🐱‍💻
