### ISSUE TITLE
Functionality for Increment Floating action button

### ISSUE THREAD

**Issue by AryanShinde** [mlscvitpune/Development-App#9]
When the increment floating action button is clicked, the counter on the home fragment should increment by one.

**Comment by Manas-33** [comment]
Hey @AryanShinde can I work on this?

**Comment by akshaymagar2003** [comment]
Hey @AryanShinde  can i get opportunity to work on this issue

**Comment by AtharvKinage** [comment]
Hey @gokhalevedant06  I want to work on this issue can you please assign me?

**Comment by AryanShinde** [comment]
hey @AtharvKinage you have another pr to work on so ill assign it to @Manas-33 for now. @Manas-33 you have 6 hours to complete the issue if not done in time, I have to assign it to @akshaymagar2003. Best of luck!
